INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('1', 'AL', 'Análisis Básico de Algoritmos', 'Conoce tiempo de ejecución de algoritmos', 10,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('2', 'AL', 'Análisis Básico de Algoritmos', 'Realiza procedimientos básicos de análisis de algoritmos', 22,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('3', 'AL', 'Estrategias de Diseño de Algoritmos', 'Aplica estrategias básicas de diseño de Algoritmos', 11,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('4', 'AL', 'Estructuras de Datos y Algoritmos Fundamentales', 'Usa algoritmos fundamentales', 52,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('5', 'AL', 'Estructuras de Datos y Algoritmos Fundamentales', 'Entiende Estructuras de datos fundamentales', 44,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('6', 'AL', 'Computabilidad y Complejidad de Autómatas Básicos', 'Maneja autómatas básicos', 95,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('7', 'AL', 'Computabilidad y Complejidad de Autómatas Básicos', 'Entiende el concepto de "complejidad" asociado a la definición de problemas', 60,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('8', 'AR', 'Lógica Digital y Sistemas Digitales', 'Conoce los Fundamentos de sistemas digitales', 90,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('9', 'AR', 'Lógica Digital y Sistemas Digitales', 'Conocer los conceptos básicos de Circuitos digitales', 50, 'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('10', 'AR', 'Representación de datos a nivel de máquina', 'Conoce los Fundamentos del manejo de datos a nivel de máquina', 90,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('11', 'AR', 'Organización de máquinas a nivel de ensamblador', 'Conoce conceptos básicos de Arquitectura de Computadores', 90,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('12', 'AR', 'Organización de máquinas a nivel de ensamblador', 'Conoce el ensamblador y su relación con los lenguajes de alto nivel', 90,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('13', 'AR', 'Arquitectura y Organización de Sistemas de Memoria', 'Conoce la forma en que se organizan los sistemas de memoria', 90,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('14', 'AR', 'Interfaces y Comunicación', 'Se familiariza con las formas de comunicación existentes en los sistemas computacionales', 90,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('15', 'AR', 'Interfaces y Comunicación', 'Conoce organizaciones de redes comunes', 100,'Habilitado');


INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('16', 'AL', 'Análisis Básico de Algoritmos', 'Analiza informalmente algoritmos específicos', 10,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('17', 'AL', 'Análisis Básico de Algoritmos', 'Utiliza notación formal para tiempo de ejecución', 10,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('18', 'AL', 'Análisis Básico de Algoritmos', 'Utiliza ecuaciones de recurrencia', 10,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('19', 'AL', 'Estrategias de Diseño de Algoritmos', 'Evalúa la aplicación de estrategias básicas en el diseño de algoritmos', 10,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('20', 'AL', 'Estrategias de Diseño de Algoritmos', 'Utiliza heurísticas para la solución de problemas', 5,'Habilitado');


INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('21', 'AL', 'Análisis Básico de Algoritmos', 'Realiza evaluaciones empíricas de algoritmos', 100,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('22', 'AL', 'Estructuras de Datos y Algoritmos Fundamentales', 'Evalúa la aplicabilidad de algoritmos en contextos particulares', 80,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('23', 'AR', 'Lógica Digital y Sistemas Digitales', 'Circuitos digitales', 10,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('24', 'AR', 'Interfaces y Comunicación', 'Identifica las capas de comunicación necesarias para el traspaso de información a través de redes de computadores.', 10,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('25', 'CN', 'Introducción a la modelación y simulación', 'Introducción a la modelación', 55,'Habilitado');
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, porcentajeLogro, estado) VALUES ('26', 'CN', 'Introducción a la modelación y simulación', 'Introducción a la simulación', 40,'Habilitado');

