INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('1', 'AL', 'Análisis Básico de Algoritmos', 'Conoce tiempo de ejecución de algoritmos', 'Habilitado', 1)
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('2', 'AL', 'Análisis Básico de Algoritmos', 'Realiza procedimientos básicos de análisis de algoritmos', 'Habilitado', 1)
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('3', 'AL', 'Estrategias de Diseño de Algoritmos', 'Aplica estrategias básicas de diseño de Algoritmos', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('4', 'AL', 'Estructuras de Datos y Algoritmos Fundamentales', 'Usa algoritmos fundamentales', 'Habilitado', );
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('5', 'AL', 'Estructuras de Datos y Algoritmos Fundamentales', 'Entiende Estructuras de datos fundamentales', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('6', 'AL', 'Computabilidad y Complejidad de Autómatas Básicos', 'Maneja autómatas básicos', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('7', 'AL', 'Computabilidad y Complejidad de Autómatas Básicos', 'Entiende el concepto de "complejidad" asociado a la definición de problemas', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('8', 'AR', 'Lógica Digital y Sistemas Digitales', 'Conoce los Fundamentos de sistemas digitales', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('9', 'AR', 'Lógica Digital y Sistemas Digitales', 'Conocer los conceptos básicos de Circuitos digitales', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('10', 'AR', 'Representación de datos a nivel de máquina', 'Conoce los Fundamentos del manejo de datos a nivel de máquina', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('11', 'AR', 'Organización de máquinas a nivel de ensamblador', 'Conoce conceptos básicos de Arquitectura de Computadores', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('12', 'AR', 'Organización de máquinas a nivel de ensamblador', 'Conoce el ensamblador y su relación con los lenguajes de alto nivel', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('13', 'AR', 'Arquitectura y Organización de Sistemas de Memoria', 'Conoce la forma en que se organizan los sistemas de memoria', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('14', 'AR', 'Interfaces y Comunicación', 'Se familiariza con las formas de comunicación existentes en los sistemas computacionales', 'Habilitado', 1);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, codigoCompetencia, estado) VALUES ('15', 'AR', 'Interfaces y Comunicación', 'Conoce organizaciones de redes comunes', 'Habilitado', 1);


INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('16', 'AL', 'Análisis Básico de Algoritmos', 'Analiza informalmente algoritmos específicos', 'Habilitado', 2);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('17', 'AL', 'Análisis Básico de Algoritmos', 'Utiliza notación formal para tiempo de ejecución', 'Habilitado', 2);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('18', 'AL', 'Análisis Básico de Algoritmos', 'Utiliza ecuaciones de recurrencia', 'Habilitado', 2);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('19', 'AL', 'Estrategias de Diseño de Algoritmos', 'Evalúa la aplicación de estrategias básicas en el diseño de algoritmos', 'Habilitado', 2);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('20', 'AL', 'Estrategias de Diseño de Algoritmos', 'Utiliza heurísticas para la solución de problemas', 'Habilitado', 2);


INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('21', 'AL', 'Análisis Básico de Algoritmos', 'Realiza evaluaciones empíricas de algoritmos', 'Habilitado', 3);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('22', 'AL', 'Estructuras de Datos y Algoritmos Fundamentales', 'Evalúa la aplicabilidad de algoritmos en contextos particulares', 'Habilitado', 3);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('23', 'AR', 'Lógica Digital y Sistemas Digitales', 'Circuitos digitales', 'Habilitado', 3);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('24', 'AR', 'Interfaces y Comunicación', 'Identifica las capas de comunicación necesarias para el traspaso de información a través de redes de computadores.', 'Habilitado', 3);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('25', 'CN', 'Introducción a la modelación y simulación', 'Introducción a la modelación', 'Habilitado', 3);
INSERT INTO syllabus.aprendizaje (codigo, categoria, subCategoria, descripcion, estado codigoCompetencia) VALUES ('26', 'CN', 'Introducción a la modelación y simulación', 'Introducción a la simulación', 'Habilitado', 3);

